### ISSUE TITLE
First argument to nodehun-sentences must be an instance of nodehun

### ISSUE THREAD

**Issue by kirkstrobeck** [rexxars/nodehun-sentences#1]
I keep getting

```bash
Error: First argument to nodehun-sentences must be an instance of nodehun
```

My code is pretty much straight from the README example

```js
var fs = require('fs');
var nodehun = require('nodehun');
var spellcheck = require('nodehun-sentences');
var exampleDictionaries = 'node_modules/nodehun/examples/dictionaries/en_US';
var hunspell = new nodehun(
  fs.readFileSync(exampleDictionaries + '/en_US.aff'),
  fs.readFileSync(exampleDictionaries + '/en_US.dic')
);

var text = 'This is some text we want to ceck for typos';

spellcheck(hunspell, text, function (err, typos) {
  console.log(err);
});
```

Not sure how to resolve, because it obviously is an instance of `nodehun`.

**Comment by rexxars** [comment]
Thanks for reporting, @kirkstrobeck!

Seems `nodehun` was finally updated to follow the node code style.
I've pushed `nodehun-sentences` 1.0.0 now, so if you update your dependency to use that, it should work again. 

Thanks again for reporting!

**Comment by kirkstrobeck** [comment]
I actually moved on to https://www.npmjs.com/package/boilerpipe integration -- it looks pretty promising. I was wondering if this project can use it, or if they do the same thing .. hmm
