### ISSUE TITLE
Issue with Unicode letters

### ISSUE THREAD

**Issue by D1LL1G4F** [rexxars/nodehun-sentences#7]
Nodehun-sentences doesn't support a majority of languages because it can't handle properly words that starts or ends with special Unicode letters (like ľĺťěž) and not to mention non-latin languages.

The problem lies in the following function for word trimming:
```
function trimWord(word) {
    var matches = word.match(/^[^\wÀ-ÿ]*([\wÀ-ÿ.]+)*[^\wÀ-ÿ]*$/i);
    word = (matches && matches[1]) || '';

    return word.replace(/^\d+$/, '');
}
```
More Unicode accent letters might be added with this little regex modification:
`var matches = word.match(/^[^\wÀ-ÿ\u00C0-\u017F]*([\wÀ-ÿ\u00C0-\u017F.]+)*[^\wÀ-ÿ\u00C0-\u017F]*$/i)`

But to proper fix (with non-latin letters), I would probably use XRegExp.

**Comment by rexxars** [comment]
I'd be more than happy to accept a pull request!

**Comment by D1LL1G4F** [comment]
I am afraid that I don't have permission to do that :(.

**Comment by D1LL1G4F** [comment]
Check PL.
